# tasks for sshd
---
- name: Install sshd
  package:
    name: openssh-server
    state: latest
  when: ansible_os_family in ["Debian", "RedHat"]
  notify:
    - All setup keys
    - Enable ssh
    - Enable sshd

- name: Setup sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify:
    - Reload ssh
    - Reload sshd
  tags: sshd_config
